flows:
  predict_skill_sentences_flow:
    params:
      input_dir: 'inputs/data/'
      data_dir: 'textkernel-files/'
      model_config_name: '2021.07.09.small'
      output_dir: 'outputs/sentence_classifier/data/skill_sentences'
      data_local: False
    run_id: 0
