# Jupytext config file

# Always pair ipynb notebooks to py:percent files
default_jupytext_formats = "ipynb,py:percent"

# Comment out magics (allows code formatting)
comment_magics = true

# Strip cell-level metadata (avoid polluting git diffs)
default_cell_metadata_filter = "-all"
