params:
  shape_url: "https://gisco-services.ec.europa.eu/distribution/v2/nuts/download/ref-nuts-2021-20m.geojson.zip"
  nuts_file: "NUTS_RG_20M_2021_4326_LEVL_1.geojson"
  output_path: "/inputs/shapefiles/"
  sentence_outputs_path: "outputs/skills_extraction/extracted_skills/2022.01.14_sentences_skills_data_lightweight.json"
  sentences_outputs_nuts_path: "outputs/tk_data_analysis_new_method/metadata_location/14.01.22/jobs_with_nuts_codes.json"
  jobad_sample_regions_dir: "outputs/tk_data_analysis_new_method/metadata_location/14.01.22/sample_filtered.json"
  epsg: 4326
